- platform: cast
  host: 192.168.10.2
- platform: cast
  host: 192.168.10.7
- platform: cast
  host: 192.168.10.13
- platform: panasonic_viera
  host: 192.168.10.44
  port: 55000
  mac: 24:EC:99:2C:D7:AC
  name: Tele du salon
#- platform: plex
#  host: 192.168.10.2
#  name: Ganoplex
# - platform: vlc
#   name: vlcpi
#   arguments: '--alsa-audio-device=hw:1,0'
- platform: mpd
  host: 192.168.10.15
# - platform: mpd
#   host: 192.168.10.12
- platform: squeezebox
  host: 192.168.10.21
  port: 9002
# - platform: squeezebox
#   host: 192.168.10.15
- platform: spotify
  client_id: !secret spotifyclient
  client_secret: !secret spotifysecret
